name: Java CI with Gradle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:8.5-jdk21
      options: --user root    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: gradle build
